modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="owlhousemodmc"
version="0.3.0"
displayName="OwlHouseModMC"
credits=""
authors="Blaziken77mw, "
description='''
Used by the magic of the isles mod
'''

[[dependencies.owlhousemodmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="magicIsles"
version="0.3.0"
displayName="Magic of the Isles"
credits=""
authors="Blaziken77mw,
description='''
Use features from The Owl House in Minecraft
'''

[[dependencies.magicisles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    sides="BOTH"



